# Generated by Django 5.0.7 on 2024-10-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

operations = [
    migrations.AddField(
        model_name='order',
        name='created_at',
        field=models.DateTimeField(auto_now_add=True),
        preserve_default=False,
    ),
]

