# Generated by Django 4.2.16 on 2025-01-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='payment_methods',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
