# Generated by Django 4.2.16 on 2025-01-16 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_order_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_accesses', to='restaurant.restaurant')),
            ],
        ),
    ]
