# Generated by Django 4.2.16 on 2025-01-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_restaurant_profile_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('JPY', 'Japanese Yen (¥)'), ('CNY', 'Chinese Yuan (¥)'), ('CHF', 'Swiss Franc (Fr)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)'), ('SAR', 'Saudi Riyal (ر.س)'), ('AED', 'UAE Dirham (د.إ)'), ('QAR', 'Qatari Riyal (ر.ق)'), ('KWD', 'Kuwaiti Dinar (د.ك)'), ('BHD', 'Bahraini Dinar (د.ب)'), ('OMR', 'Omani Rial (ر.ع)'), ('EGP', 'Egyptian Pound (ج.م)'), ('JOD', 'Jordanian Dinar (د.ا)'), ('LBP', 'Lebanese Pound (ل.ل)'), ('IQD', 'Iraqi Dinar (ع.د)'), ('TRY', 'Turkish Lira (₺)'), ('INR', 'Indian Rupee (₹)'), ('PKR', 'Pakistani Rupee (₨)'), ('RUB', 'Russian Ruble (₽)'), ('SGD', 'Singapore Dollar (S$)'), ('HKD', 'Hong Kong Dollar (HK$)'), ('MYR', 'Malaysian Ringgit (RM)'), ('IDR', 'Indonesian Rupiah (Rp)'), ('THB', 'Thai Baht (฿)'), ('KRW', 'South Korean Won (₩)')], default='EUR', help_text='Select the currency for menu prices', max_length=10),
        ),
    ]
